# This file is for custom makefile targets at the project level.
# They are meant to be share by the whole project team.

## -- Project targets ----------------------------------------------------------------------------------------------- ##

.PHONY: test-notebooks
test-notebooks: ## Execute test notebooks using pytest and nbval
	$(ENV_COMMAND_TOOL) nox -s test_nb
